services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    hostname: dragonfly
    privileged: true
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"