services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    hostname: dragonfly
    privileged: true
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge